# Generated by Django 2.2.5 on 2020-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('list', models.CharField(max_length=336)),
            ],
        ),
    ]
